#!/usr/bin/env python3
"""Build a CVPR/NeurIPS-style architecture diagram for the ICPA cotton project.

The figure uses real HD pre/post UAV imagery and the image-derived 2.5D map
views generated by the project. Solid arrows show the implemented proxy
pipeline. Dashed arrows show calibration-dependent branches that should not be
claimed as completed metric 3D without scale/camera validation.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Rectangle
from PIL import Image, ImageOps


REPO_ROOT = Path("/Volumes/T9/ICPA")
DEFAULT_PRE_RGB = REPO_ROOT / "outputs/figures/hd_prepost_3d_maps/pre-defoliation_rgb_hd.png"
DEFAULT_POST_RGB = REPO_ROOT / "outputs/figures/hd_prepost_3d_maps/post-defoliation_rgb_hd.png"
DEFAULT_PRE_MAP = REPO_ROOT / "outputs/figures/clean_aerial_cotton_representation/pre-defoliation_aerial_2p5d_map_clean.png"
DEFAULT_POST_MAP = REPO_ROOT / "outputs/figures/clean_aerial_cotton_representation/post-defoliation_aerial_2p5d_map_clean.png"
DEFAULT_OUT_DIR = REPO_ROOT / "outputs/figures/cvpr_architecture"


INK = "#23272f"
MUTED = "#606876"
LINE = "#374151"
BLACK = "#111111"
BLUE = "#2f6fd6"
GREEN = "#2e8b57"
VIOLET = "#7b55c7"
ORANGE = "#c27624"
GOLD = "#c7952c"
GRAY_BORDER = "#9aa4b2"
SOFT_BLUE = "#edf4ff"
SOFT_GREEN = "#edf8f1"
SOFT_VIOLET = "#f4efff"
SOFT_ORANGE = "#fff4e8"
SOFT_GOLD = "#fff8df"
SOFT_GRAY = "#f7f8fa"


def configure_fonts() -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def load_image(path: Path, *, crop: tuple[float, float, float, float] | None = None) -> Image.Image:
    image = Image.open(path).convert("RGB")
    if crop:
        w, h = image.size
        l, t, r, b = crop
        image = image.crop((int(l * w), int(t * h), int(r * w), int(b * h)))
    return image


def add_image(
    ax,
    image: Image.Image,
    xy: tuple[float, float],
    box: tuple[float, float],
    label: str,
    *,
    label_location: str = "top",
) -> None:
    x, y = xy
    w, h = box
    fitted = ImageOps.fit(
        image,
        (900, 620),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )
    ax.imshow(
        fitted,
        extent=(x, x + w, y, y + h),
        aspect="auto",
        zorder=3,
    )
    ax.add_patch(
        Rectangle(
            (x, y),
            w,
            h,
            linewidth=1.25,
            edgecolor=BLACK,
            facecolor="none",
            zorder=4,
        )
    )
    if label_location == "bottom":
        ax.text(x + w / 2, y - 0.012, label, ha="center", va="top", fontsize=9.0, fontweight="bold", color=INK)
    else:
        ax.text(x + w / 2, y + h + 0.012, label, ha="center", va="bottom", fontsize=9.0, fontweight="bold", color=INK)


def add_box(
    ax,
    xy: tuple[float, float],
    size: tuple[float, float],
    title: str,
    body: str,
    edge: str,
    fill: str,
    *,
    dashed: bool = False,
) -> None:
    x, y = xy
    w, h = size
    patch = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.006,rounding_size=0.013",
        linewidth=1.35,
        edgecolor=edge,
        facecolor=fill,
        linestyle="--" if dashed else "-",
        zorder=4,
    )
    ax.add_patch(patch)
    title_lines = title.count("\n") + 1
    title_font = 7.8 if title_lines == 1 else 7.1
    body_y = y + h - (0.052 if title_lines == 1 else 0.066)
    ax.text(
        x + w / 2,
        y + h - 0.020,
        title,
        ha="center",
        va="top",
        fontsize=title_font,
        fontweight="bold",
        color=INK,
        linespacing=0.95,
        zorder=5,
    )
    ax.text(x + w / 2, body_y, body, ha="center", va="top", fontsize=5.8, color=INK, linespacing=1.16, zorder=5)


def arrow(
    ax,
    start,
    end,
    *,
    dashed: bool = False,
    color: str = LINE,
    rad: float = 0.0,
    lw: float = 1.45,
    zorder: float = 6.0,
    mutation_scale: float = 13.0,
) -> None:
    patch = FancyArrowPatch(
        start,
        end,
        arrowstyle="-|>",
        mutation_scale=mutation_scale,
        linewidth=lw,
        color=color,
        linestyle="--" if dashed else "-",
        connectionstyle=f"arc3,rad={rad}",
        shrinkA=0,
        shrinkB=0,
        zorder=zorder,
    )
    ax.add_patch(patch)


def boundary_arrow(
    ax,
    start: tuple[float, float],
    end: tuple[float, float],
    *,
    dashed: bool = False,
    color: str = LINE,
    lw: float = 1.45,
    mutation_scale: float = 10.5,
) -> None:
    """Draw a connector whose endpoints are the exact object boundaries."""
    arrow(ax, start, end, dashed=dashed, color=color, lw=lw, zorder=6.0, mutation_scale=mutation_scale)


def add_arrow_legend(ax, xy: tuple[float, float]) -> None:
    x, y = xy
    w, h = 0.198, 0.088
    patch = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.006,rounding_size=0.010",
        linewidth=0.95,
        edgecolor="#cbd5df",
        facecolor="#fbfcfd",
        zorder=2,
    )
    ax.add_patch(patch)
    ax.text(x + 0.012, y + h - 0.018, "Arrow convention", ha="left", va="top", fontsize=7.3, fontweight="bold", color=INK, zorder=5)
    arrow(ax, (x + 0.016, y + 0.043), (x + 0.063, y + 0.043), color=LINE, lw=1.25, zorder=6)
    ax.text(x + 0.073, y + 0.043, "implemented proxy path", ha="left", va="center", fontsize=6.2, color=MUTED, zorder=5)
    arrow(ax, (x + 0.016, y + 0.020), (x + 0.063, y + 0.020), dashed=True, color=LINE, lw=1.25, zorder=6)
    ax.text(x + 0.073, y + 0.020, "calibration-only validation", ha="left", va="center", fontsize=6.2, color=MUTED, zorder=5)


def poly_arrow(ax, points: list[tuple[float, float]], *, dashed: bool = False, color: str = LINE, lw: float = 1.45) -> None:
    if len(points) < 2:
        return
    for start, end in zip(points[:-2], points[1:-1]):
        ax.plot(
            [start[0], end[0]],
            [start[1], end[1]],
            color=color,
            linewidth=lw,
            linestyle="--" if dashed else "-",
            zorder=3.2,
        )
    arrow(ax, points[-2], points[-1], dashed=dashed, color=color, lw=lw)


def build_diagram(args: argparse.Namespace) -> Path:
    configure_fonts()
    pre_rgb = load_image(args.pre_rgb, crop=(0.02, 0.08, 0.98, 0.88))
    post_rgb = load_image(args.post_rgb, crop=(0.02, 0.08, 0.98, 0.88))
    pre_map = load_image(args.pre_map, crop=(0.02, 0.10, 0.98, 0.86))
    post_map = load_image(args.post_map, crop=(0.02, 0.10, 0.98, 0.86))

    fig, ax = plt.subplots(figsize=(17.0, 7.9), dpi=args.dpi)
    fig.patch.set_facecolor("white")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    ax.text(
        0.500,
        0.982,
        "Mask-Guided Cotton Boll Phenotyping Architecture",
        ha="center",
        va="top",
        fontsize=18.0,
        fontweight="bold",
        color=INK,
    )
    ax.text(
        0.500,
        0.946,
        "Pre/post-defoliation UAV imagery \u2192 detector-prompted lint masks \u2192 proxy 2.5D review \u2192 conservative trait summaries",
        ha="center",
        va="top",
        fontsize=10.8,
        color=MUTED,
    )

    # Input evidence.
    ax.text(0.035, 0.890, "A. Pre/post UAV imagery", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    add_image(ax, pre_rgb, (0.040, 0.654), (0.165, 0.190), "Pre-defoliation RGB")
    add_image(ax, post_rgb, (0.040, 0.384), (0.165, 0.190), "Post-defoliation RGB")

    # Top implemented pipeline.
    ax.text(0.240, 0.890, "B. Implemented proxy pipeline", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    y_top = 0.745
    bw = 0.097
    bh = 0.122
    gap = 0.021
    xs = [0.240 + i * (bw + gap) for i in range(6)]
    titles = [
        "1. Phase resolver",
        "2. Candidate detector",
        "3. Prompted lint-mask\nextraction",
        "4. Readiness scorer",
        "5. Proxy 2.5D review",
        "6. Trait and plot\naggregation",
    ]
    bodies = [
        "Folder label or canopy\ngreenness assigns\npre/post phase",
        "CLAHE, top-hat response,\nconnected components,\nand color gates",
        "Detector boxes guide\nlint segmentation and\ngreen-canopy suppression",
        "Ranks candidates by lint fraction,\nvisibility, brightness, shape,\nsize, green penalty, and phase",
        "Maps retained pixels\nto image-derived\nvisibility-height surface",
        "Reports count, visibility,\nmask axes, diameter proxy,\nvolume proxy, confidence,\nand plot-cell summaries",
    ]
    colors = [(BLUE, SOFT_BLUE), (GREEN, SOFT_GREEN), (VIOLET, SOFT_VIOLET), (ORANGE, SOFT_ORANGE), (BLUE, SOFT_BLUE), (GREEN, SOFT_GREEN)]
    for x, title, body, (edge, fill) in zip(xs, titles, bodies, colors):
        add_box(ax, (x, y_top), (bw, bh), title, body, edge, fill)
    for i in range(5):
        boundary_arrow(ax, (xs[i] + bw, y_top + bh / 2), (xs[i + 1], y_top + bh / 2))

    # Single clean input arrow from the image group boundary to the phase resolver.
    input_group_right = 0.205
    boundary_arrow(ax, (input_group_right, y_top + bh / 2), (xs[0], y_top + bh / 2))

    # Visual/proxy outputs.
    ax.text(0.240, 0.596, "C. Proxy review and phenotyping outputs", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    record_x, record_y, record_w, record_h = 0.792, 0.408, 0.165, 0.154
    add_box(
        ax,
        (record_x, record_y),
        (record_w, record_h),
        "Structured phenotyping record",
        "Candidate traits: visibility,\nmask axes, diameter proxy,\nellipsoid volume proxy,\nreadiness score, and phase.\nPlot traits: cell count and\nmean proxy traits over the\nimage-coordinate grid.",
        GRAY_BORDER,
        SOFT_GRAY,
    )
    pre_map_xy = (0.460, 0.402)
    post_map_xy = (0.622, 0.402)
    map_size = (0.148, 0.175)
    add_image(ax, pre_map, pre_map_xy, map_size, "Pre-defoliation proxy 2.5D", label_location="bottom")
    add_image(ax, post_map, post_map_xy, map_size, "Post-defoliation proxy 2.5D", label_location="bottom")

    proxy_center = (xs[4] + bw / 2, y_top)
    pre_map_center_x = pre_map_xy[0] + map_size[0] / 2
    post_map_center_x = post_map_xy[0] + map_size[0] / 2
    map_top_y = pre_map_xy[1] + map_size[1]
    boundary_arrow(ax, proxy_center, (pre_map_center_x, map_top_y))
    boundary_arrow(ax, proxy_center, (post_map_center_x, map_top_y))
    record_center_x = record_x + record_w / 2
    trait_center_x = xs[5] + bw / 2
    boundary_arrow(ax, (trait_center_x, y_top), (record_center_x, record_y + record_h), color=LINE)

    # Calibration branch.
    add_arrow_legend(ax, (0.782, 0.253))

    ax.text(0.240, 0.328, "D. Calibration-dependent validation branch", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    add_box(
        ax,
        (0.240, 0.136),
        (0.220, 0.130),
        "Optional calibrated geometry",
        "Use only with scale,\ncamera intrinsics, pose,\nGCP/RTK, RGB-D, SfM/MVS,\nDUSt3R/MASt3R/VGGT,\nor validated 3DGS evidence.",
        GOLD,
        SOFT_GOLD,
        dashed=True,
    )
    add_box(
        ax,
        (0.500, 0.136),
        (0.180, 0.130),
        "Metric trait validation",
        "Report trait MAE/RMSE,\nmask IoU, reprojection\nconsistency, Chamfer distance,\nand plot-cell agreement.",
        GOLD,
        SOFT_GOLD,
        dashed=True,
    )
    boundary_arrow(ax, (0.460, 0.201), (0.500, 0.201), dashed=True, color=LINE)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    png = args.out_dir / "mask_guided_cotton_architecture_cvpr_hd.png"
    pdf = args.out_dir / "mask_guided_cotton_architecture_cvpr_hd.pdf"
    svg = args.out_dir / "mask_guided_cotton_architecture_cvpr_hd.svg"
    fig.savefig(png, bbox_inches="tight", pad_inches=0.08)
    fig.savefig(pdf, bbox_inches="tight", pad_inches=0.08)
    fig.savefig(svg, bbox_inches="tight", pad_inches=0.08)
    plt.close(fig)
    return png


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pre-rgb", type=Path, default=DEFAULT_PRE_RGB)
    parser.add_argument("--post-rgb", type=Path, default=DEFAULT_POST_RGB)
    parser.add_argument("--pre-map", type=Path, default=DEFAULT_PRE_MAP)
    parser.add_argument("--post-map", type=Path, default=DEFAULT_POST_MAP)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--dpi", type=int, default=240)
    return parser.parse_args()


def main() -> None:
    path = build_diagram(parse_args())
    print(f"architecture_png={path}")


if __name__ == "__main__":
    main()
