#!/usr/bin/env python3
"""Build a CVPR/NeurIPS-style architecture diagram for the ICPA cotton project.

The figure uses real HD pre/post UAV imagery and the image-derived 2.5D map
views generated by the project. Solid arrows show the implemented proxy
pipeline. Dashed arrows show calibration-dependent branches that should not be
claimed as completed metric 3D without scale/camera validation.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Rectangle
from PIL import Image, ImageOps


REPO_ROOT = Path("/Volumes/T9/ICPA")
DEFAULT_PRE_RGB = REPO_ROOT / "outputs/figures/hd_prepost_3d_maps/pre-defoliation_rgb_hd.png"
DEFAULT_POST_RGB = REPO_ROOT / "outputs/figures/hd_prepost_3d_maps/post-defoliation_rgb_hd.png"
DEFAULT_PRE_MAP = REPO_ROOT / "outputs/figures/clean_aerial_cotton_representation/pre-defoliation_aerial_2p5d_map_clean.png"
DEFAULT_POST_MAP = REPO_ROOT / "outputs/figures/clean_aerial_cotton_representation/post-defoliation_aerial_2p5d_map_clean.png"
DEFAULT_OUT_DIR = REPO_ROOT / "outputs/figures/cvpr_architecture"


INK = "#23272f"
MUTED = "#606876"
LINE = "#374151"
BLUE = "#2f6fd6"
GREEN = "#2e8b57"
VIOLET = "#7b55c7"
ORANGE = "#c27624"
GOLD = "#c7952c"
GRAY_BORDER = "#9aa4b2"
SOFT_BLUE = "#edf4ff"
SOFT_GREEN = "#edf8f1"
SOFT_VIOLET = "#f4efff"
SOFT_ORANGE = "#fff4e8"
SOFT_GOLD = "#fff8df"
SOFT_GRAY = "#f7f8fa"


def configure_fonts() -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def load_image(path: Path, *, crop: tuple[float, float, float, float] | None = None) -> Image.Image:
    image = Image.open(path).convert("RGB")
    if crop:
        w, h = image.size
        l, t, r, b = crop
        image = image.crop((int(l * w), int(t * h), int(r * w), int(b * h)))
    return image


def add_image(
    ax,
    image: Image.Image,
    xy: tuple[float, float],
    box: tuple[float, float],
    label: str,
    *,
    label_location: str = "top",
) -> None:
    x, y = xy
    w, h = box
    pad = 0.007
    frame = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.004,rounding_size=0.008",
        linewidth=1.15,
        edgecolor=GRAY_BORDER,
        facecolor="white",
        zorder=2,
    )
    ax.add_patch(frame)
    fitted = ImageOps.fit(
        image,
        (900, 620),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5),
    )
    ax.imshow(
        fitted,
        extent=(x + pad, x + w - pad, y + pad, y + h - pad),
        aspect="auto",
        zorder=3,
    )
    if label_location == "bottom":
        ax.text(x + w / 2, y - 0.012, label, ha="center", va="top", fontsize=9.0, fontweight="bold", color=INK)
    else:
        ax.text(x + w / 2, y + h + 0.012, label, ha="center", va="bottom", fontsize=9.0, fontweight="bold", color=INK)


def add_box(
    ax,
    xy: tuple[float, float],
    size: tuple[float, float],
    title: str,
    body: str,
    edge: str,
    fill: str,
    *,
    dashed: bool = False,
) -> None:
    x, y = xy
    w, h = size
    patch = FancyBboxPatch(
        (x, y),
        w,
        h,
        boxstyle="round,pad=0.010,rounding_size=0.014",
        linewidth=1.35,
        edgecolor=edge,
        facecolor=fill,
        linestyle="--" if dashed else "-",
        zorder=4,
    )
    ax.add_patch(patch)
    ax.text(x + 0.012, y + h - 0.022, title, ha="left", va="top", fontsize=8.9, fontweight="bold", color=INK, zorder=5)
    ax.text(x + 0.012, y + h - 0.055, body, ha="left", va="top", fontsize=6.5, color=INK, linespacing=1.18, zorder=5)


def arrow(ax, start, end, *, dashed: bool = False, color: str = LINE, rad: float = 0.0, lw: float = 1.45) -> None:
    patch = FancyArrowPatch(
        start,
        end,
        arrowstyle="-|>",
        mutation_scale=13.0,
        linewidth=lw,
        color=color,
        linestyle="--" if dashed else "-",
        connectionstyle=f"arc3,rad={rad}",
        shrinkA=3,
        shrinkB=3,
        zorder=6,
    )
    ax.add_patch(patch)


def poly_arrow(ax, points: list[tuple[float, float]], *, dashed: bool = False, color: str = LINE, lw: float = 1.45) -> None:
    if len(points) < 2:
        return
    for start, end in zip(points[:-2], points[1:-1]):
        ax.plot(
            [start[0], end[0]],
            [start[1], end[1]],
            color=color,
            linewidth=lw,
            linestyle="--" if dashed else "-",
            zorder=6,
        )
    arrow(ax, points[-2], points[-1], dashed=dashed, color=color, lw=lw)


def build_diagram(args: argparse.Namespace) -> Path:
    configure_fonts()
    pre_rgb = load_image(args.pre_rgb, crop=(0.02, 0.08, 0.98, 0.88))
    post_rgb = load_image(args.post_rgb, crop=(0.02, 0.08, 0.98, 0.88))
    pre_map = load_image(args.pre_map, crop=(0.02, 0.10, 0.98, 0.86))
    post_map = load_image(args.post_map, crop=(0.02, 0.10, 0.98, 0.86))

    fig, ax = plt.subplots(figsize=(17.0, 9.2), dpi=args.dpi)
    fig.patch.set_facecolor("white")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")

    ax.text(0.5, 0.965, "Mask-Guided Cotton Boll Phenotyping Architecture", ha="center", va="center", fontsize=21, fontweight="bold", color=INK)
    ax.text(
        0.5,
        0.925,
        "Pre/post-defoliation UAV imagery → detector-prompted lint masks → morphology 2.5D review → conservative trait summaries",
        ha="center",
        va="center",
        fontsize=10.5,
        color=MUTED,
    )

    # Input evidence.
    ax.text(0.045, 0.862, "Inputs: aerial visibility intervention", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    add_image(ax, pre_rgb, (0.045, 0.637), (0.150, 0.185), "Pre-defoliation RGB")
    add_image(ax, post_rgb, (0.045, 0.378), (0.150, 0.185), "Post-defoliation RGB")

    # Top implemented pipeline.
    ax.text(0.250, 0.862, "Implemented proxy pipeline", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    y_top = 0.715
    bw = 0.096
    bh = 0.122
    gap = 0.018
    xs = [0.250 + i * (bw + gap) for i in range(6)]
    titles = [
        "1. Phase resolver",
        "2. Candidate detector",
        "3. Prompted lint mask",
        "4. Readiness score",
        "5. Proxy 2.5D review",
        "6. Trait + plot output",
    ]
    bodies = [
        "Folder label or ExG\ngreenness assigns\npre/post phase.",
        "CLAHE, top-hat,\nOtsu components,\nand color gates.",
        "Box-prompted lint\nmask; suppress green\ncanopy/residue.",
        "Rank candidates by\nlint, visibility,\nshape, size, phase.",
        "Map retained pixels\nto image-derived\nvisibility surface.",
        "Count, visibility,\nL/W/D, volume proxy,\nconfidence, grid cell.",
    ]
    colors = [(BLUE, SOFT_BLUE), (GREEN, SOFT_GREEN), (VIOLET, SOFT_VIOLET), (ORANGE, SOFT_ORANGE), (BLUE, SOFT_BLUE), (GREEN, SOFT_GREEN)]
    for x, title, body, (edge, fill) in zip(xs, titles, bodies, colors):
        add_box(ax, (x, y_top), (bw, bh), title, body, edge, fill)
    for i in range(5):
        arrow(ax, (xs[i] + bw, y_top + bh / 2), (xs[i + 1], y_top + bh / 2))

    # Clean input arrows to phase resolver.
    junction = (0.222, y_top + bh / 2)
    arrow(ax, (0.195, 0.730), junction, color=LINE)
    arrow(ax, (0.195, 0.470), junction, color=LINE)
    arrow(ax, junction, (xs[0], y_top + bh / 2), color=LINE)

    # Evidence and outputs row.
    ax.text(0.250, 0.595, "Evidence and outputs", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    record_x, record_y, record_w, record_h = 0.800, 0.407, 0.155, 0.128
    add_box(
        ax,
        (record_x, record_y),
        (record_w, record_h),
        "Structured phenotyping record",
        "Candidate table: mask, visibility,\naxes, diameter proxy, volume proxy,\nreadiness, phase, plot cell.",
        GRAY_BORDER,
        SOFT_GRAY,
    )
    add_image(ax, pre_map, (0.500, 0.382), (0.135, 0.175), "Pre-defoliation proxy 2.5D", label_location="bottom")
    add_image(ax, post_map, (0.648, 0.382), (0.135, 0.175), "Post-defoliation proxy 2.5D", label_location="bottom")

    # Evidence arrows use a small bus above the visual panels so labels and
    # map views stay unobstructed in the final paper figure.
    proxy_center = (xs[4] + bw / 2, y_top)
    pre_map_center_x = 0.500 + 0.135 / 2
    post_map_center_x = 0.648 + 0.135 / 2
    map_top_y = 0.382 + 0.175
    bus_y = 0.592
    ax.plot([proxy_center[0], proxy_center[0]], [proxy_center[1], bus_y], color=LINE, linewidth=1.45, zorder=6)
    ax.plot([pre_map_center_x, proxy_center[0]], [bus_y, bus_y], color=LINE, linewidth=1.45, zorder=6)
    arrow(ax, (pre_map_center_x, bus_y), (pre_map_center_x, map_top_y), color=LINE)
    arrow(ax, (post_map_center_x, bus_y), (post_map_center_x, map_top_y), color=LINE)
    arrow(ax, (xs[5] + bw / 2, y_top), (record_x + record_w / 2, record_y + record_h), color=LINE)

    # Calibration branch.
    ax.text(0.250, 0.300, "Calibration-dependent branch", ha="left", va="bottom", fontsize=11.2, fontweight="bold", color=INK)
    add_box(
        ax,
        (0.250, 0.140),
        (0.220, 0.130),
        "Optional calibrated geometry",
        "Only used when scale, camera intrinsics,\npose, GCP/RTK, RGB-D, SfM/MVS,\nDUSt3R/MASt3R/VGGT, or validated\n3DGS evidence is available.",
        GOLD,
        SOFT_GOLD,
        dashed=True,
    )
    add_box(
        ax,
        (0.505, 0.140),
        (0.180, 0.130),
        "Metric trait validation",
        "Report trait MAE/RMSE,\nmask IoU, reprojection\nconsistency, Chamfer distance,\nand plot-cell agreement.",
        GOLD,
        SOFT_GOLD,
        dashed=True,
    )
    arrow(ax, (0.470, 0.205), (0.505, 0.205), dashed=True, color=LINE)

    # Legend and boundary.
    ax.plot([0.045, 0.865], [0.088, 0.088], color="#d7dde5", linewidth=1.0)
    ax.text(0.045, 0.055, "Solid arrows: implemented MVP/proxy analysis.  Dashed arrows: calibration-dependent validation path.", fontsize=8.7, color=MUTED, ha="left")
    ax.text(0.045, 0.030, "Scientific boundary: 2.5D maps are image-derived aerial visibility surfaces; metric boll geometry requires calibrated scale/camera validation.", fontsize=8.7, color=MUTED, ha="left")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    png = args.out_dir / "mask_guided_cotton_architecture_cvpr_hd.png"
    pdf = args.out_dir / "mask_guided_cotton_architecture_cvpr_hd.pdf"
    svg = args.out_dir / "mask_guided_cotton_architecture_cvpr_hd.svg"
    fig.savefig(png, bbox_inches="tight", pad_inches=0.08)
    fig.savefig(pdf, bbox_inches="tight", pad_inches=0.08)
    fig.savefig(svg, bbox_inches="tight", pad_inches=0.08)
    plt.close(fig)
    return png


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pre-rgb", type=Path, default=DEFAULT_PRE_RGB)
    parser.add_argument("--post-rgb", type=Path, default=DEFAULT_POST_RGB)
    parser.add_argument("--pre-map", type=Path, default=DEFAULT_PRE_MAP)
    parser.add_argument("--post-map", type=Path, default=DEFAULT_POST_MAP)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--dpi", type=int, default=240)
    return parser.parse_args()


def main() -> None:
    path = build_diagram(parse_args())
    print(f"architecture_png={path}")


if __name__ == "__main__":
    main()
